name: MERN CI

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Seed MongoDB
        working-directory: ./backend
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: node seedtaskdata.js

      - name: Run Jest tests
        working-directory: ./backend
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: npm test -- --runInBand